title: Pub Games Club!
markdown: kramdown
# markdown: GFM
url: "https://pubgames.club"

# localization
# language: "en"
languages: ["en", "de"]
  
# for atom feed
author:
  name: Brian Junker-Latocha
  email: brian@junker-latocha.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # - jekyll-multiple-languages-plugin

collections_dir: content
collections:
  posts:
    output: true


defaults:
  - scope:
      path: "_posts/de"
    values:
      layout: "post_de"
      permalink: /de/:title/
  - scope:
      path: "_posts/en"
    values:
      layout: "post"
      permalink: /:title/



  

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]



